name: 01 Simple Starter Workflow
on:
  push:
jobs:
  hello_job:
    runs-on: ubuntu-latest

    steps:
      - name: command 1
        run: echo "Welcome to Github Actions!!!"
      - name: command 2
        run: echo "Learning Github Actions!!!"
      - name: command 3
        run: pwd
